trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'SSH - VM Ansible'
    playbookSourceRemoteMachine: 'agentMachine'
    playbookRootRemoteMachine: '$(System.DefaultWorkingDirectory)'
    playbookPathLinkedArtifactOnRemoteMachine: 'users.yml'
    inventoriesRemoteMachine: 'file'
    inventoryFileSourceRemoteMachine: 'agentMachine'
    inventoryFileLinkedArtifactOnRemoteMachine: 'azure_rm.yml'
    args: '--private-key ~/.ssh/ansible_rsa'